version: '3.8'


services:
  weather_service:
    build: ./weather_service
    container_name: weather_service
    ports:
      - "8001:8001"
    environment:
      - API_KEY=${API_KEY}
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8000:8000"
    depends_on:
      - weather_service
    restart: always
  
  #anomaly_detection_service:
  #  build: ./anomaly_detection_service
  #  ports: ["8002:8002"]

  #nlu_service:
  #  build: ./nlu_service
  #  ports: ["8005:8005"]

  #logging_service:
  #  build: ./logging_service
  #  ports: ["8004:8004"]

  #notification_service:
  #  build: ./notification_service
  #  ports: ["8006:8006"]

  #cache_service:
  #  build: ./cache_service
  #  ports: ["8003:8003"]
